type Position {
  id: ID!
  created_at: String!
  name: String!
}

type PaginatedPositions {
  items: [Position!]!
  total: Int!
  page: Int!
  limit: Int!
  total_pages: Int!
}

type Query {
  positions(params: SearchPaginationInput): PaginatedPositions!
  position(id: ID!): Position!
}

input CreatePositionInput {
  name: String!
}

input UpdatePositionInput {
  positionId: ID!
  name: String!
}

input DeletePositionInput {
  positionId: ID!
}

type Mutation {
  createPosition(position: CreatePositionInput!): Position!
  updatePosition(position: UpdatePositionInput!): Position!
  deletePosition(position: DeletePositionInput!): DeleteResult!
}
