type Department {
  id: ID!
  created_at: String!
  name: String!
}

type PaginatedDepartments {
  items: [Department!]!
  total: Int!
  page: Int!
  limit: Int!
  total_pages: Int!
}

type Query {
  departments(params: SearchPaginationInput): PaginatedDepartments!
}

input CreateDepartmentInput {
  name: String!
}

input UpdateDepartmentInput {
  departmentId: ID!
  name: String!
}

input DeleteDepartmentInput {
  departmentId: ID!
}

type Mutation {
  createDepartment(department: CreateDepartmentInput!): Department!
  updateDepartment(department: UpdateDepartmentInput!): Department!
  deleteDepartment(department: DeleteDepartmentInput!): DeleteResult!
}
