type Skill {
  id: ID!
  created_at: String!
  name: String!
  category: SkillCategory
  category_name: String
  category_parent_name: String
}

type PaginatedSkills {
  items: [Skill!]!
  total: Int!
  page: Int!
  limit: Int!
  total_pages: Int!
}

type Query {
  skills(params: SearchPaginationInput): PaginatedSkills!
}

input CreateSkillInput {
  name: String!
  categoryId: ID
}

input UpdateSkillInput {
  skillId: ID!
  name: String!
  categoryId: ID
}

input DeleteSkillInput {
  skillId: ID!
}

type Mutation {
  createSkill(skill: CreateSkillInput!): Skill!
  updateSkill(skill: UpdateSkillInput!): Skill!
  deleteSkill(skill: DeleteSkillInput!): DeleteResult!
}
